name: "Validations"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:

  Static-Analysis:
    name: "Static analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap

      - name: Run static analysis
        run: make static-analysis


  Unit-Test:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap

      - name: Run unit tests
        run: go test -race -coverprofile=${{ github.workspace }}/coverage.txt ./...

      - name: Check coverage
        run: |
          go tool cover -func=${{ github.workspace }}/coverage.txt | tail -1
          python3 .github/scripts/coverage.py 28 ${{ github.workspace }}/coverage.txt